name: Quality Coding -- English Wikipedia 2014 10k sample
source: enwiki 2014 revisions -- 10k random sample
author:
    name: Aaron Halfaker
    email: aaron.halfaker@gmail.com

coder:
    class: revcoding.coders.RevisionDiff
    form:
        fields:
            - damaging
            - good-faith
            - edit type

fields:
    damaging:
        class: revcoding.ui.RadioButtons
        label: Damaging?
        help: Did this edit cause damage to the article?
        options:
            -
                label: yes
                value: yes
                tooltip: Yes, this edit is damaging and should be reverted.
            -
                label: no
                value: no
                tooltip: >
                         No, this edit is not damaging and should not be
                         reverted.
            -
                label: unsure
                value: unsure
                tooltip: >
                         It's not clear whether this edit damages the article or
                         not.
    good-faith:
        class: revcoding.ui.RadioButtons
        label: Good faith?
        help: >
              Does it appear as though the author of this edit was
              trying to contribute productively?
        options:
            -
                label: yes
                value: yes
                tooltip: Yes, this edit appears to have been made in good-faith.
            -
                label: no
                value: no
                tooltip: No, this edit appears to have been made in bad-faith.
            -
                label: unsure
                value: unsure
                tooltip: >
                         It's not clear whether or not this edit was made in
                         good-faith.
    edit type:
        class: revcoding.ui.CheckButtons
        label: Edit type
        help: >
              What types of changes does the edit effect?  Select all that
              apply or none if none apply.
        options:
            -
                label: content addition
                value: copy edit
                tooltip: This edit adds content to the article.
            -
                label: copy edit
                value: copy edit
                tooltip: This edit fixes the copy of the article.
            -
                label: damage removal
                value: damage removal
                tooltip: This edit removes damage to the article.
            -
                label: formatting
                value: formatting
                tooltip: >
                         This edit changes the location and/or size of copy,
                         infoboxes, tables, or other article elements.
            -
                label: categorizing
                value: categorizing
                tooltip: >
                         This edit purposefully changes how the article is
                         categorized.
            -
                label: adds references
                value: adds references
                tooltip: This edit adds a new reference to the article.
            -
                label: refactoring
                value: refactoring
                tooltip: >
                         This edit moves content that was already present in
                         the article.
            -
                label: curation
                value: curation
                tooltip: >
                         This edit flags problems (e.g. cleanup templates) or
                         performs other types of coordination work work.
