database:
  host: localhost
  user: revcoding
  database: revcoding
  password: revcoding-admin

form_directory: forms/enabled
application_root: "/labels"
url_prefix: "/labels"


oauth:
  mw_uri: https://www.mediawiki.org/w/index.php
  key: <snip>
  secret: <snip>
