database:
  host: localhost
  user: wikilabels
  database: wikilabels
  password: wikilabels-admin

form_directory: forms/enabled
application_root: "/labels"
url_prefix: "/labels"


oauth:
  mw_uri: https://www.mediawiki.org/w/index.php
  key: <snip>
  secret: <snip>
