wikilabels:
  form_directory: forms/enabled

wsgi:
  host: localhost:8080
  application_root: "/labels"
  url_prefix: "/labels"

database:
  host: localhost
  user: wikilabels
  database: wikilabels
  password: wikilabels-admin

oauth:
  mw_uri: https://www.mediawiki.org/w/index.php
  creds: config/oauth-localdev.yaml
